// Drive the lifter: parse function entries from decompiled_all.c, lift each
// (bounded by the next entry's address), write generated/all.js +
// generated/manifest.json.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { loadPE } from "../harness/loader.js";
import { liftFunction } from "./lift.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const RCT_EXE = resolve(ROOT, "binary/rct.exe");
const DECOMP = "/tmp/rct_work/decompiled_all.c";
const OUT_DIR = resolve(ROOT, "generated");
const OUT_JS = resolve(OUT_DIR, "all.js");
const OUT_MANIFEST = resolve(OUT_DIR, "manifest.json");

mkdirSync(OUT_DIR, { recursive: true });

// --- parse function entries
const decompText = readFileSync(DECOMP, "utf8");
const HEADER = /\/\/ ===== (FUN_[0-9a-f]+) @ ([0-9a-f]+) \(section ([^)]+)\)/g;
const entries = [];
let m;
while ((m = HEADER.exec(decompText)) !== null) {
  entries.push({ name: m[1], addr: parseInt(m[2], 16), section: m[3] });
}
entries.sort((a, b) => a.addr - b.addr);
console.log(`Parsed ${entries.length} function entries.`);

// --- load binary
const image = loadPE(RCT_EXE);
const memory = new Uint8Array(image.totalSize);
memory.set(image.memory, 0);

// --- lift each
const manifest = [];
const liftedFns = [];
let counts = { lifted: 0, indirect: 0, unsupported: 0, outOfBounds: 0, error: 0 };
let totalInsts = 0;

for (let i = 0; i < entries.length; i++) {
  const e = entries[i];
  // Bound: from this addr to next entry's addr (or +500 bytes if last).
  const endAddr = (i + 1 < entries.length) ? entries[i + 1].addr : (e.addr + 500);
  // Only lift code-section functions.
  if (e.section !== ".text" && e.section !== "CODESEG" && e.section !== "CodeSeg") {
    manifest.push({ ...e, status: "skip", reason: `section=${e.section}` });
    continue;
  }
  const r = liftFunction(memory, e.addr, endAddr);
  counts[r.status] = (counts[r.status] || 0) + 1;
  if (r.status === "lifted") {
    liftedFns.push(r.jsSource);
    totalInsts += r.instCount;
    manifest.push({ ...e, status: "lifted", instCount: r.instCount, byteSize: r.byteSize });
  } else {
    manifest.push({ ...e, status: r.status, reason: r.reason });
  }
}

console.log("Status counts:");
for (const [k, v] of Object.entries(counts)) {
  console.log(`  ${k.padEnd(12)} ${v}`);
}
console.log(`Total instructions in lifted bodies: ${totalInsts}`);

// --- write outputs
const liftedAddrs = manifest.filter((x) => x.status === "lifted").map((x) => x.addr);
const dispatchTable = liftedAddrs
  .map((a) => `  0x${a.toString(16)}: fn_${a.toString(16).padStart(8, "0")},`)
  .join("\n");

const jsHeader = `// AUTO-GENERATED by rct-js/lifter/cli.js — do not edit by hand.
// Regenerate with: npm run lift
// Lifted functions: ${liftedAddrs.length}

import {
  mem8, mem16, mem32, write8, write16, write32,
  read8reg, write8reg, read16reg, write16reg,
  ror32, rol32, shl32, shr32, sar32,
  signExtend8, signExtend16,
  setLogicFlags, setSubFlags, setAddFlags,
  dispatch, stepInterp,
} from "../lifter/runtime.js";

`;

const jsBody = liftedFns.join("\n\n");
const jsFooter = `

export const lifted = {
${dispatchTable}
};
`;

writeFileSync(OUT_JS, jsHeader + jsBody + jsFooter);
writeFileSync(OUT_MANIFEST, JSON.stringify(manifest, null, 2));

console.log(`\nWrote ${OUT_JS}  (${(jsHeader.length + jsBody.length + jsFooter.length).toLocaleString()} bytes)`);
console.log(`Wrote ${OUT_MANIFEST}  (${manifest.length} entries)`);
