// AUTO-GENERATED by tools/gen-win32-barrel.js — do not edit by hand.
//
// Stub Win32 functions that are imported by ported/auto/*.js but not yet
// implemented. Each returns 0 and warns once. As real implementations land
// in runtime/win32/<dll>.js, the corresponding name disappears from this
// file on the next regeneration.

const _warned = new Set();
function stub(name) {
  return (heap, ...args) => {
    if (!_warned.has(name)) {
      _warned.add(name);
      if (typeof console !== "undefined") {
        console.warn("[runtime/win32 stub]", name);
      }
    }
    return 0;
  };
}

export const _abort = stub("_abort");
export const _lclose = stub("_lclose");
export const _lopen = stub("_lopen");
export const _lread = stub("_lread");
export const _memset = stub("_memset");
export const _strcmp = stub("_strcmp");
export const _strlen = stub("_strlen");
export const _strncat = stub("_strncat");
export const _strncpy = stub("_strncpy");
export const _strrchr = stub("_strrchr");
export const builtin_strncpy = stub("builtin_strncpy");
export const cpuid_Version_info = stub("cpuid_Version_info");
export const func_0x00430934 = stub("func_0x00430934");
export const int = stub("int");
export const int3 = stub("int3");
export const mciSendStringA = stub("mciSendStringA");
export const midiOutGetDevCapsA = stub("midiOutGetDevCapsA");
export const midiOutGetNumDevs = stub("midiOutGetNumDevs");
export const midiOutGetVolume = stub("midiOutGetVolume");
export const midiOutSetVolume = stub("midiOutSetVolume");
export const mmioAdvance = stub("mmioAdvance");
export const mmioAscend = stub("mmioAscend");
export const mmioClose = stub("mmioClose");
export const mmioCreateChunk = stub("mmioCreateChunk");
export const mmioDescend = stub("mmioDescend");
export const mmioGetInfo = stub("mmioGetInfo");
export const mmioOpenA = stub("mmioOpenA");
export const mmioRead = stub("mmioRead");
export const mmioSeek = stub("mmioSeek");
export const mmioSetInfo = stub("mmioSetInfo");
export const mmioWrite = stub("mmioWrite");
export const ram0x005f8539 = stub("ram0x005f8539");
export const ram0x00971e88 = stub("ram0x00971e88");
export const ram0x0099aa8c = stub("ram0x0099aa8c");
export const register0x00000010 = stub("register0x00000010");
export const swi = stub("swi");
export const timeBeginPeriod = stub("timeBeginPeriod");
export const timeEndPeriod = stub("timeEndPeriod");
export const timeGetTime = stub("timeGetTime");
export const timeKillEvent = stub("timeKillEvent");
export const timeSetEvent = stub("timeSetEvent");
export const uRam00999fda = stub("uRam00999fda");
export const uRam0099a01c = stub("uRam0099a01c");
export const uint3 = stub("uint3");
export const ulonglong = stub("ulonglong");
export const undefined3 = stub("undefined3");
export const wsprintfA = stub("wsprintfA");
