// AUTO-GENERATED by tools/gen-win32-barrel.js — do not edit by hand.
//
// Stub Win32 functions that are imported by ported/auto/*.js but not yet
// implemented. Each returns 0 and warns once. As real implementations land
// in runtime/win32/<dll>.js, the corresponding name disappears from this
// file on the next regeneration.

const _warned = new Set();
function stub(name) {
  return (heap, ...args) => {
    if (!_warned.has(name)) {
      _warned.add(name);
      if (typeof console !== "undefined") {
        console.warn("[runtime/win32 stub]", name);
      }
    }
    return 0;
  };
}


