// Parse Wine .spec files into a single JS lookup table.
// Output: harness/win32_specs.js
//
// Each spec line:  <ordinal>  <conv>  [flags...]  Name(args...)  [handler]
// We extract: name, ordinal, argCount.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SPECS_DIR = "/tmp/wine_specs";
// (Wine_dll_filename, RCT-import_dll_name) — RCT imports use original-case names.
const DLLS = [
  ["user32",   "USER32.dll"],
  ["gdi32",    "GDI32.dll"],
  ["advapi32", "ADVAPI32.dll"],
  ["kernel32", "KERNEL32.dll"],
  ["comdlg32", "comdlg32.dll"],
  ["shell32",  "SHELL32.dll"],
  ["ole32",    "ole32.dll"],
  ["winmm",    "WINMM.dll"],
  ["dinput",   "DINPUT.dll"],
  ["dsound",   "DSOUND.dll"],
  ["dplayx",   "DPLAYX.dll"],
];

const out = {}; // "DLL!Name" -> argCount
const ordinals = {}; // "DLL!#N" -> argCount  (separate so we can lookup by ordinal)

for (const [wineName, dllName] of DLLS) {
  const text = readFileSync(join(SPECS_DIR, wineName + ".spec"), "utf8");
  for (const lineRaw of text.split("\n")) {
    const line = lineRaw.replace(/#.*$/, "").trim();
    if (!line) continue;
    // Tokenize keeping the (args) intact.
    const m = /^(\S+)\s+(\w+)(?:\s+(-\S+))*\s*([A-Za-z_][\w$]*)\(([^)]*)\)/.exec(line);
    if (!m) {
      // Lines like "extern gdwDPlaySPRefCount" or "variable" — skip.
      continue;
    }
    const ordinal = m[1];
    const conv    = m[2];
    const fnName  = m[4];
    const argList = m[5].trim();
    if (conv === "stub" || conv === "extern" || conv === "variable" || conv === "forward") continue;
    // Args are space-separated tokens. Empty list = 0 args.
    const argCount = argList.length === 0 ? 0 : argList.split(/\s+/).length;
    out[`${dllName}!${fnName}`] = argCount;
    if (/^\d+$/.test(ordinal)) {
      ordinals[`${dllName}!#${ordinal}`] = argCount;
    }
  }
  console.error(`Parsed ${wineName}.spec`);
}

const totalNamed = Object.keys(out).length;
const totalOrdinal = Object.keys(ordinals).length;

const output = `// AUTO-GENERATED by tools/parse_wine_specs.js — do not edit by hand.
// Source: Wine .spec files (from gitlab.winehq.org/wine/wine).
// Total: ${totalNamed} named exports, ${totalOrdinal} ordinal-callable exports.
//
// Lookup: argCount(\`DLL.dll!FunctionName\`) or argCount(\`DLL.dll!#1\`).

export const WIN32_SPECS = {
${Object.entries(out)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`)
  .join("\n")}

  // ---- Ordinal-only exports ----
${Object.entries(ordinals)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`)
  .join("\n")}
};
`;

writeFileSync("/Users/joelrobinson/rct-js/harness/win32_specs.js", output);
console.error(`Wrote harness/win32_specs.js: ${totalNamed} named + ${totalOrdinal} ordinal entries.`);
